version: '3'

networks:
  nostr:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:db8:a::/64
          gateway: fd00:db8:a::1
services:
  mint:
    image: cashubtc/nutshell:0.15.3
    container_name: mint
    ports:
      - "3338"
    networks:
      nostr:
    environment:
      - MINT_BACKEND_BOLT11_SAT=FakeWallet
      - MINT_LISTEN_HOST=0.0.0.0
      - MINT_LISTEN_PORT=3338
      - MINT_PRIVATE_KEY=TEST_PRIVATE_KEY
      - MINT_INFO_DESCRIPTION=This Cashu test mint has no public IP address and can only be reached via NWS powered by Nostr
      - MINT_INFO_NAME=Cashu NWS mint
    command: ["poetry", "run", "mint"]
  exit:
    build:
      context: .
    container_name: exit
    command: [ "./nws","exit" ]
    networks:
      nostr:
    environment:
      - NOSTR_RELAYS=ws://nostr-relay:7777
      - NOSTR_PRIVATE_KEY=
      - BACKEND_HOST=mint:3338
    depends_on:
      - mint
      - nostr
  exit-https:
    build:
      context: .
    container_name: exit-https
    command: ["./nws","exit","--port", "4443", "--target", "http://mint:3338"]
    networks:
      nostr:
    environment:
      - NOSTR_RELAYS=ws://nostr-relay:7777
      - NOSTR_PRIVATE_KEY=
      - BACKEND_HOST=:4443
    depends_on:
      - mint
      - nostr
  entry:
    build:
      context: .
    command: [ "./nws","entry"]
    container_name: entry
    ports:
      - 8882:8882
    networks:
      nostr:
    environment:
      - NOSTR_RELAYS=ws://nostr-relay:7777
    depends_on:
      - nostr
  nostr:
    image: carroarmato0/strfry:latest
    container_name: nostr-relay
    ports:
      - 7777:7777
    networks:
      nostr:
    restart: always
    volumes:
      - ./strfry/data:/app/strfry-db/:Z
      - ./strfry/strfry.conf:/app/strfry.conf:ro,Z
