name: tests

on: [  pull_request ]

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Golang run tests
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - uses: codecov/codecov-action@v3
        with:
          verbose: true # optional (default = false)